### ISSUE TITLE
Endpoint Connections fail due to lack of TLS 1.2

### ISSUE THREAD

**Issue by brandonspell08** [tlindsay42/ArmorPowerShell#153]
## Problem Statement

Connecting to endpoints throw error 'The request was aborted: Could not create SSL/TLS secure channel.'

## Steps to Reproduce

1. EConnect-armor -credential "username"
1. See error
```Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At C:\Users\bspell\Google
Drive\GITHUB\ArmorPowerShell-master\ArmorPowerShell-master\Armor\Private\Invoke-ArmorRestMethod.ps1:122 char:24
+ ...  $request = Invoke-WebRequest -Uri $Uri -Headers $Headers -Method $Me ...
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

ScriptHalted
At C:\Users\bspell\Google
Drive\GITHUB\ArmorPowerShell-master\ArmorPowerShell-master\Armor\Private\Invoke-ArmorRestMethod.ps1:130 char:13
+             throw $request.StatusDescription
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

1. [...]

## Expected Behavior

Return Armorsession variable

## Environment

Any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

### Armor PowerShell Module Version

```powershell
Get-Module -ListAvailable -Name 'Armor'
Version
-------
1.0.317
```

### PowerShell Version

```powershell
Get-PSVersion

Name                           Value
----                           -----
PSVersion                      5.1.15063.1805
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1805
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Operating System

List operating system details (eg: distribution, version, build).

## Additional Context

Add any other context or screenshots about the problem here.

**Comment by brandonspell08** [comment]
Proposed solution:
adding the following to armor.psm1
```
if( [Net.ServicePointManager]::SecurityProtocol -notmatch "TLS12" ) {
    [Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12
}

```

**Comment by tlindsay42** [comment]
Hi @brandonspell08!

Nice! Would you be willing to submit a pull request with a few OCD adjustments to match the style of the project?

1. A space between the `if` statement and the open parenthesis
1. Single-quotes instead of double since there is no string interpolation.
1. Adjust the case of the pattern.

#### Example

```powershell
if ( [Net.ServicePointManager]::SecurityProtocol -notmatch 'Tls12' ) {
    [Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12
}
```

Thanks for using the Armor PowerShell module and for reporting the issue!

**Comment by brandonspell08** [comment]
Sorry, I'm still really new to working with Github. I Cloned the master Repo and tried creating a branch called 'TLS12support' but I get an 'Authentication failed error'. Is that the correct procedure I should be following?

![image](https://user-images.githubusercontent.com/20215364/58723387-8ec7ac80-839f-11e9-8c23-16f3c59d2ac5.png)

**Comment by tlindsay42** [comment]
No worries! Here's one way:

1. Fork the repo to create a copy that you have full control over.
1. Normally, you would clone your fork instead of my repo since you don't have direct access, but since you already have a clone, you can adjust your remote repo mappings in your existing clone, by running the following:

    ```sh
    git remote rename origin upstream
    git remote add origin https://github.com/brandonspell08/ArmorPowerShell.git
    ```

1. Normally, you would create the branch now, but you can keep the one that you already have in your local clone
1. Make the change(s) & commit to the branch
1. When ready, push the change to your forked repo, which will publish the branch (creating the branch in your fork) with `git push origin`
1. Back on your fork's site: https://github.com/brandonspell08/ArmorPowerShell, you will now be prompted to submit your pull request to the master branch in my repo.
1. When the pull request is submitted, the continuous integration that I have configured will be triggered to run all of the applicable tests in AppVeyor and Travis CI, and code coverage will be scored. Now that I think about it, we should write a quick Pester test too to make sure that this feature isn't broken by a future change and to keep the score at 100%. Adding a test [here](/tlindsay42/ArmorPowerShell/blob/master/tests/config/Module.Tests.ps1) that disables TLS 1.2 (if enabled), then import the module, and then tests to make sure that TLS 1.2 has been re-enabled should do it.
1. Anyway, when I accept the pull request, the change will be pulled into the master branch of my repo.
1. Optionally, you can then:
    1. Pull the updated master branch from the upstream remote (my repo) into your local (cloned) repo's master branch with `git pull upstream`, so that your local copy is up to date for any future branches
    1. Delete your local branch that has been merged with `git branch -d TLS12support`
    1. Push the updated master branch to your fork so that your fork is now up to date too with `git push origin`
    1. Delete the merged branch in your fork with `git push --delete origin TLS12support`
1. Voila! You're done!

**Comment by brandonspell08** [comment]
First of all, phenomenal job on this module!!!
Secondly, I'm still getting my feet wet with Pester Testing. I tried following the logic of the testing format, but its just too confusing for me :(  
Could you take a look at my work? https://github.com/brandonspell08/ArmorPowerShell/blob/TLS12/tests/config/Module.Tests.ps1

**Comment by tlindsay42** [comment]
Thanks much and no worries at all. You had it, but I tweaked it to make it more efficient since we're already force re-importing the module in the first test:

```powershell
    Context -Name 'Import' -Fixture {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11

        It -Name "should import module: '${Global:CI_MODULE_NAME}'" -Test {
            { Import-Module -Name $CI_MODULE_MANIFEST_PATH -Force } |
                Should -Not -Throw
        }

        It -Name 'should enable TLS 1.2' -Test {
            [Net.ServicePointManager]::SecurityProtocol |
                Should -Match 'Tls12'
        }
    }
```

So, we now start the test context by removing Tls12 as an accepted security protocol type for this PowerShell session, then we force re-import the module in the first test as usual, and then test to make sure that TLS 1.2 was enabled.

Also, you can enable AppVeyor & Travis CI for your fork for free since it is an open source project. It isn't necessary, but since my test fixtures are designed for CI integration, it will make it easier to see what happens when you make a change, as well as to learn.

**Comment by tlindsay42** [comment]
Checking in.  Need any help with the pull request, @brandonspell08?

**Comment by brandonspell08** [comment]
Sorry, just got back from vacation. I submitted the pull request. I started playing around with Appveyor, but I have a lot to learn. This is a whole new level of powershell for me!

**Comment by tlindsay42** [comment]
Sorry for the delay and thanks again for the contribution!
